FixFactorSystem/Models/NewPhone.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FixFactorSystem.Models
{
    public partial class NewPhone
    {
        public int Id { get; set; }
        public string MobName { get; set; }
        public string Ram { get; set; }
        public string Storage { get; set; }
        public int? Price { get; set; }
        public string Image { get; set; }
        [NotMapped]
        public IFormFile File { get; set; }
    }
}

FixFactorSystem/Controllers/NewPhonesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FixFactorSystem.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace FixFactorSystem.Controllers
{
  
    public class NewPhonesController : Controller
    {
        private readonly PhoneShopContext _context;
        private readonly IWebHostEnvironment hosting;
        public NewPhonesController(PhoneShopContext context, IWebHostEnvironment hosting)
        {
            _context = context;
            this.hosting = hosting;
        }

        // GET: NewPhones
        //[Authorize(Roles = "Admin")]
       
        public async Task<IActionResult> Index()
        {
            return View(await _context.NewPhone.ToListAsync());
        }

        // GET: NewPhones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newPhone = await _context.NewPhone
                .FirstOrDefaultAsync(m => m.Id == id);
            if (newPhone == null)
            {
                return NotFound();
            }

            return View(newPhone);
        }

        // GET: NewPhones/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: NewPhones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
      //  [Authorize(Roles ="Admin")]
        public async Task<IActionResult> Create([Bind("Id,MobName,Ram,Storage,Price,File")] NewPhone newPhone)
        {
            if (ModelState.IsValid)
            {
              

              //  string FileName = string.Empty;
                if (newPhone.File != null)
                {


                     String rotpath = hosting.WebRootPath;
                     string fileName = Path.GetFileNameWithoutExtension(newPhone.File.FileName);
                     string extention = Path.GetExtension(newPhone.File.FileName);
                     newPhone.Image = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extention;
                     string path = Path.Combine(rotpath + "/Mobimg", fileName);

                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await newPhone.File.CopyToAsync(fileStream);
                       
                    }

                    





                    //  string NewPhones = Path.Combine(hosting.WebRootPath, "Mobimg");
                    //  FileName = newPhone.File.FileName;

                    //   string fullpath = Path.Combine(NewPhones, FileName);
                    //  newPhone.File.CopyTo(new FileStream(fullpath, FileMode.Create));


                    //   newPhone.Image = FileName;

                    _context.Add(newPhone);
                    await _context.SaveChangesAsync();
                   // TempData["mydata"] = _context;
              
                //  return RedirectToAction("Index");
                 return   RedirectToAction("Create", "NewPhoneDetails", "newPhone");
                }
            }
            return View(newPhone);
        }

        // GET: NewPhones/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newPhone = await _context.NewPhone.FindAsync(id);
            if (newPhone == null)
            {
                return NotFound();
            }
            return View(newPhone);
        }

        // POST: NewPhones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MobName,Ram,Storage,Price,File")] NewPhone newPhone)
        {
            if (id != newPhone.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (newPhone.File != null)
                    {


                        String rotpath = hosting.WebRootPath;
                        string fileName = Path.GetFileNameWithoutExtension(newPhone.File.FileName);
                        string extention = Path.GetExtension(newPhone.File.FileName);
                        newPhone.Image = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extention;
                        string path = Path.Combine(rotpath + "/Mobimg", fileName);

                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            await newPhone.File.CopyToAsync(fileStream);

                        }



                        _context.Update(newPhone);
                        await _context.SaveChangesAsync();
                    }
                }

                catch (DbUpdateConcurrencyException)
                {
                    if (!NewPhoneExists(newPhone.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(newPhone);
        }

        // GET: NewPhones/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newPhone = await _context.NewPhone
                .FirstOrDefaultAsync(m => m.Id == id);
            if (newPhone == null)
            {
                return NotFound();
            }

            return View(newPhone);
        }


      
           
        

        // POST: NewPhones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var newPhone = await _context.NewPhone.FindAsync(id);
            _context.NewPhone.Remove(newPhone);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NewPhoneExists(int id)
        {
            return _context.NewPhone.Any(e => e.Id == id);
        }
    }
}

FixFactorSystem/Views/NewPhones/Create.cshtml
@model FixFactorSystem.Models.NewPhone

@{
    ViewData["Title"] = "Create";
}


<div class="container">
   

    <h2 style="color:blueviolet; margin:20px;font-weight:bold">اضافة هاتف جديد</h2>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                  النوع
                    <input asp-for="MobName" class="form-control" />
                    <span asp-validation-for="MobName" class="text-danger"></span>
                </div>
                <div class="form-group">
                  الرام
                    <input asp-for="Ram" class="form-control" />
                    <span asp-validation-for="Ram" class="text-danger"></span>
                </div>
                <div class="form-group">
                 التخزين
                    <input asp-for="Storage" class="form-control" />
                    <span asp-validation-for="Storage" class="text-danger"></span>
                </div>
                <div class="form-group">
             السعر
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                  الصوره
                    <input type="file" name="File" asp-for="File" class="form-control" />
                    <span asp-validation-for="File" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="اضافه" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div >
        <a style="color:blueviolet" asp-action="Index">عوده</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FixFactorSystem/Views/NewPhones/Delete.cshtml
@model FixFactorSystem.Models.NewPhone

@{
    ViewData["Title"] = "Delete";
}
<div class="container">
    <h2 style="color:blueviolet; margin:20px;font-weight:bold">مسح الهاتف</h2>
    <h3>هل تريد مسح الهاتف</h3>
    <div>
       
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
          النوع
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.MobName)
            </dd>
            <dt class="col-sm-2">
         الرام
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Ram)
            </dd>
            <dt class="col-sm-2">
      التخزين
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Storage)
            </dd>
            <dt class="col-sm-2">
             السعر
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Price)
            </dd>
            <dt class="col-sm-2">
     
            </dt>
            <dd class="col-sm-10">
                @if (Model.Image != null)
                {


                    <img src="~/Mobimg/@Model.Image" style="width:300px; height:450px" />
                }

            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="مسح" class="btn btn-danger" /> |
            <a asp-action="Index">عوده</a>
        </form>
    </div>
</div>

FixFactorSystem/Views/NewPhones/Details.cshtml
@model FixFactorSystem.Models.NewPhone

@{
    ViewData["Title"] = "Details";
}


<div class="features" style="        font-family: “Droid Arabic Kufi”, serif;
        color: #7c795d;
        margin: 5px;
        direction: rtl;
        text-align: right;
">
    <div class="container">
        <div class="feat" style=" float: right; width:50%">

            <h1 style="        color: darkmagenta ;
        text-align: right; direction: rtl;
        margin: 10px;
        font-weight: bold">
                تفاصيل
            </h1>

            <dl class="row" style=" direction:rtl; ">
                <dt class="col-sm-2">
                    اسم الهاتف
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.MobName)
                </dd>
                <dt class="col-sm-2">
                    رام
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Ram)
                </dd>
                <dt class="col-sm-2">
                    التخزين
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Storage)
                </dd>
                <dt class="col-sm-2">
                    السعر
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Price) جنيه
                </dd>


            </dl>
        </div>
        <div class="feat" style=" float: right; width:50%">
            <dl>
                <dt class="col-sm-2">
                  
                </dt>
                <dd>
                    @if (Model.Image != null)
                    {


                        <img src="~/Mobimg/@Model.Image" style="width:300px; height:450px" />
                    }
                </dd>

            </dl>
        </div>
        <div class="ff" style="margin-bottom:700px;">

            <div>
                <a style="color:blueviolet" asp-action="Edit" asp-route-id="@Model.Id">تعديل </a> |
                <a style="color:blueviolet" asp-action="Index">رجوع</a>
            </div>
        </div>
    </div>



    


</div>











        
  

FixFactorSystem/Views/NewPhones/Edit.cshtml
@model FixFactorSystem.Models.NewPhone

@{
    ViewData["Title"] = "Edit";
}
<div class="container">
    

    <h2  style="color:blueviolet; margin:20px;font-weight:bold">تعديل مواصفات هاتف جديد</h2>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                النوع
                    <input asp-for="MobName" class="form-control" />
                    <span asp-validation-for="MobName" class="text-danger"></span>
                </div>
                <div class="form-group">
               الرام
                    <input asp-for="Ram" class="form-control" />
                    <span asp-validation-for="Ram" class="text-danger"></span>
                </div>
                <div class="form-group">
                التخزين
                    <input asp-for="Storage" class="form-control" />
                    <span asp-validation-for="Storage" class="text-danger"></span>
                </div>
                <div class="form-group">
                السعر
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    الصوره
                    <input type="file" name="File" asp-for="File" class="form-control" />
                    <span asp-validation-for="File" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="حفظ" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a style="color:blueviolet" asp-action="Index">عوده</a>
    </div>
    </div>
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

FixFactorSystem/Views/NewPhones/Index.cshtml
@model IEnumerable<FixFactorSystem.Models.NewPhone>

@{
    ViewData["Title"] = "Index";
}
<link href="~/PhoneStyleSheet.css" rel="stylesheet" />

<div class="m" style=" background-color: #c7e3f1;">
<div class="features">
    <div class="container">
       
        <div class="title">

            <h1 style="font-family: “Droid Arabic Kufi”, serif;color:blueviolet; text-align: center; margin-left: 400px;">هواتف جديده</h1>


            








                <form class="c" style="margin-left: 400px;" asp-controller="NewPhones" asp-action="Create">

                    <input type="submit" value="اضافه" class="btn btn-primary" />
                </form>


           


            <form class="d" asp-controller="NewPhoneDetails" asp-action="Index">

                <input type="submit" value="مواصفات الأجهزه" class="btn btn-success" />
            </form>


        </div>
    </div>
</div>


<div class="crr" >
    <div class="container" >
        <div class="row" style="width: 87%; text-align:right">
            @foreach (var item in Model)
            {
                <div class="col-4" >


                    <div class="card bg-primary" style="height:500px;width:300px;float:left;margin:2px; ">
                        <div class="card-img">
                            <img class="card-img-top" style="height:250px;width:300px;" src="@("/Mobimg/" + item.Image)    ">
                        </div>
                        <div class="card-body" style="font-weight:bold;">
                            <h5 class="card-title text-black" style=" color: white; font-weight:bold;">   @Html.DisplayFor(modelItem => item.MobName): النوع  </h5>
                            <h5 class="card-text" style=" color: white; font-weight:bold;">     @Html.DisplayFor(modelItem => item.Ram):  الرام</h5>
                            <h5 class="card-text" style=" color: white; font-weight:bold;">       @Html.DisplayFor(modelItem => item.Storage): التخزين</h5>
                            <h5 class="card-text" style=" color: white; font-weight:bold;">     السعر :  @Html.DisplayFor(modelItem => item.Price)  جنيه</h5>


                          
                         
                            <!--   <a asp-controller="NewPhoneDetails"
    asp-action="Index"> Details</a>-->
                            <tr>
                                <td>
                                    <a asp-action="Edit" style="color:brown" asp-route-id="@item.Id">تعديل</a> |
                                    <a asp-action="Details"style="color:brown" asp-route-id="@item.Id">تفاصيل</a> |
                                    <a asp-action="Delete" style="color:brown" asp-route-id="@item.Id">مسح</a>
                                </td>
                            </tr>
                        </div>

                    </div>

                   
                </div>
            }



        </div>
    </div>

</div>

    </div>