FixFactorSystem/Models/UsedPhoneDetails.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FixFactorSystem.Models
{
    public partial class UsedPhoneDetails
    {
        public int Idu { get; set; }
        public string MobNameu { get; set; }
        public string Ramu { get; set; }
        public string Storageu { get; set; }
        public string Camerau { get; set; }
        public string Imgu { get; set; }
        public string Color { get; set; }
        public string Display { get; set; }
        public string Battary { get; set; }
        public string AddDetails { get; set; }
        public int Price { get; set; }

        [NotMapped]
        public IFormFile File { get; set; }
    }
}

FixFactorSystem/Controllers/UsedPhoneDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FixFactorSystem.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace FixFactorSystem.Controllers
{
    public class UsedPhoneDetailsController : Controller
    {
        private readonly PhoneShopContext _context;
        private readonly IWebHostEnvironment hosting;
        public UsedPhoneDetailsController(PhoneShopContext context, IWebHostEnvironment hosting)
        {
            _context = context;
            this.hosting = hosting;
        }

        // GET: UsedPhoneDetails
        public async Task<IActionResult> Index()
        {
            return View(await _context.UsedPhoneDetails.ToListAsync());
        }

        // GET: UsedPhoneDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usedPhoneDetails = await _context.UsedPhoneDetails
                .FirstOrDefaultAsync(m => m.Idu == id);
            if (usedPhoneDetails == null)
            {
                return NotFound();
            }

            return View(usedPhoneDetails);
        }

        // GET: UsedPhoneDetails/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UsedPhoneDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Idu,MobNameu,Ramu,Storageu,Camerau,File,Color,Display,Battary,AddDetails,Price")] UsedPhoneDetails usedPhoneDetails)
        {
            if (ModelState.IsValid)
            {
                if (usedPhoneDetails.File != null)
                {


                    String rotpath = hosting.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(usedPhoneDetails.File.FileName);
                    string extention = Path.GetExtension(usedPhoneDetails.File.FileName);
                    usedPhoneDetails.Imgu = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extention;
                    string path = Path.Combine(rotpath + "/Mobimg", fileName);

                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await usedPhoneDetails.File.CopyToAsync(fileStream);

                    }


                    _context.Add(usedPhoneDetails);
                    await _context.SaveChangesAsync();
                    // NewPhone newPhone = TempData["mydata"] as NewPhone;
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(usedPhoneDetails);
        }

        // GET: UsedPhoneDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usedPhoneDetails = await _context.UsedPhoneDetails.FindAsync(id);
            if (usedPhoneDetails == null)
            {
                return NotFound();
            }
            return View(usedPhoneDetails);
        }

        // POST: UsedPhoneDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Idu,MobNameu,Ramu,Storageu,Camerau,File,Color,Display,Battary,AddDetails,Price")] UsedPhoneDetails usedPhoneDetails)
        {
            if (id != usedPhoneDetails.Idu)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (usedPhoneDetails.File != null)
                    {


                        String rotpath = hosting.WebRootPath;
                        string fileName = Path.GetFileNameWithoutExtension(usedPhoneDetails.File.FileName);
                        string extention = Path.GetExtension(usedPhoneDetails.File.FileName);
                        usedPhoneDetails.Imgu = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extention;
                        string path = Path.Combine(rotpath + "/Mobimg", fileName);

                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            await usedPhoneDetails.File.CopyToAsync(fileStream);

                        }
                        _context.Update(usedPhoneDetails);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsedPhoneDetailsExists(usedPhoneDetails.Idu))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usedPhoneDetails);
        }

        // GET: UsedPhoneDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usedPhoneDetails = await _context.UsedPhoneDetails
                .FirstOrDefaultAsync(m => m.Idu == id);
            if (usedPhoneDetails == null)
            {
                return NotFound();
            }

            return View(usedPhoneDetails);
        }

        // POST: UsedPhoneDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usedPhoneDetails = await _context.UsedPhoneDetails.FindAsync(id);
            _context.UsedPhoneDetails.Remove(usedPhoneDetails);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsedPhoneDetailsExists(int id)
        {
            return _context.UsedPhoneDetails.Any(e => e.Idu == id);
        }
    }
}

FixFactorSystem/Views/UsedPhoneDetails/Create.cshtml
@model FixFactorSystem.Models.UsedPhoneDetails

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2 style="color:blueviolet; margin:20px;font-weight:bold">اضافة هاتف مستعمل</h2>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                  النوع
                    <input asp-for="MobNameu" class="form-control" />
                    <span asp-validation-for="MobNameu" class="text-danger"></span>
                </div>
                <div class="form-group">
                  الرام
                    <input asp-for="Ramu" class="form-control" />
                    <span asp-validation-for="Ramu" class="text-danger"></span>
                </div>
                <div class="form-group">
                التخزين
                    <input asp-for="Storageu" class="form-control" />
                    <span asp-validation-for="Storageu" class="text-danger"></span>
                </div>
                <div class="form-group">
             الكاميرا
                    <input asp-for="Camerau" class="form-control" />
                    <span asp-validation-for="Camerau" class="text-danger"></span>
                </div>
                <div class="form-group">
               صورة
                    <input type="file" name="File" asp-for="File" class="form-control" />
                    <span asp-validation-for="File" class="text-danger"></span>
                </div>
                <div class="form-group">
                اللون
                    <input asp-for="Color" class="form-control" />
                    <span asp-validation-for="Color" class="text-danger"></span>
                </div>
                <div class="form-group">
            الشاشة
                    <input asp-for="Display" class="form-control" />
                    <span asp-validation-for="Display" class="text-danger"></span>
                </div>
                <div class="form-group">
             البطارية
                    <input asp-for="Battary" class="form-control" />
                    <span asp-validation-for="Battary" class="text-danger"></span>
                </div>
                <div class="form-group">
                مواصفات اخرى
                    <input asp-for="AddDetails" class="form-control" />
                    <span asp-validation-for="AddDetails" class="text-danger"></span>
                </div>
                <div class="form-group">
               السعر
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="اضافة" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a style="color:blueviolet" asp-action="Index">عودة</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

FixFactorSystem/Views/UsedPhoneDetails/Delete.cshtml
@model FixFactorSystem.Models.UsedPhoneDetails

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2 style="color:blueviolet; margin:20px;font-weight:bold">مسح الهاتف</h2>
    <h3>هل تريد مسح الهاتف</h3>
    <div>
     
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                النوع
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.MobNameu)
            </dd>
            <dt class="col-sm-2">
                الرام
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Ramu)
            </dd>
            <dt class="col-sm-2">
                التخزين
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Storageu)
            </dd>
            <dt class="col-sm-2">
                الكاميرا
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Camerau)
            </dd>

            <dt class="col-sm-2">
                اللون
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Color)
            </dd>
            <dt class="col-sm-2">
                الشاشه
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Display)
            </dd>
            <dt class="col-sm-2">
                البطاريه
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Battary)
            </dd>
            <dt class="col-sm-2">
                مواصفات اخرى
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.AddDetails)
            </dd>
            <dt class="col-sm-2">
                السعر
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Price)
            </dd>
            <dt class="col-sm-2">

            </dt>
            <dd class="col-sm-10">
                @if (Model.Imgu != null)
                {


                    <img src="~/Mobimg/@Model.Imgu" style="width:300px; height:450px" />
                }

            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="Idu" />
            <input type="submit" value="مسح" class="btn btn-danger" /> |
            <a asp-action="Index">عودة</a>
        </form>
    </div>
</div>

FixFactorSystem/Views/UsedPhoneDetails/Details.cshtml
@model FixFactorSystem.Models.UsedPhoneDetails

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">

    <div class="features" style="        font-family: “Droid Arabic Kufi”, serif;
        color: #7c795d;
        margin: 5px;
        direction: rtl;
        text-align: right;
">
        <div class="container">
            <div class="feat" style=" float: right; width:50%">

                <h1 style="        color: darkmagenta ;
        text-align: right; direction: rtl;
        margin: 10px;
        font-weight: bold">
                    تفاصيل
                </h1>

                <dl class="row" style=" direction:rtl; ">
                    <dt class="col-sm-2">
                        النوع
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.MobNameu)
                    </dd>
                    <dt class="col-sm-2">
                        الرام
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Ramu)
                    </dd>
                    <dt class="col-sm-2">
                        التخزين
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Storageu)
                    </dd>
                    <dt class="col-sm-2">
                        الكاميرا
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Camerau)
                    </dd>

                    <dt class="col-sm-2">
                        اللون
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Color)
                    </dd>
                    <dt class="col-sm-2">
                        الشاشة
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Display)
                    </dd>
                    <dt class="col-sm-2">
                        البطارية
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Battary) مللي أمبير
                    </dd>
                    <dt class="col-sm-2">
                        مواصفات اخرى
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.AddDetails)
                    </dd>
                    <dt class="col-sm-2">
                        السعر
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Price) جنيه
                    </dd>
                    
                </dl>
            </div>
            <div class="feat" style=" float: right; width:50%">
                <dl>
                    <dt class="col-sm-2">

                    </dt>
                    <dd class="col-sm-10">
                        @if (Model.Imgu != null)
                        {


                            <img src="~/Mobimg/@Model.Imgu" style="width:300px; height:450px" />
                        }
                    </dd>
                </dl>
            </div>
        </div>
        <div class="ff" style=" margin-right:250px; margin-bottom:700px;">
            <a style="color:blueviolet" asp-action="Edit" asp-route-id="@Model.Idu">تعديل</a> |
            <a style="color:blueviolet" asp-action="Index">عودة</a>
        </div>
    </div>

FixFactorSystem/Views/UsedPhoneDetails/Edit.cshtml
@model FixFactorSystem.Models.UsedPhoneDetails

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    <h2 style="color:blueviolet; margin:20px;font-weight:bold">تعديل مواصفات الهاتف</h2>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Idu" />
                <div class="form-group">
                النوع
                    <input asp-for="MobNameu" class="form-control" />
                    <span asp-validation-for="MobNameu" class="text-danger"></span>
                </div>
                <div class="form-group">
                 الرام
                    <input asp-for="Ramu" class="form-control" />
                    <span asp-validation-for="Ramu" class="text-danger"></span>
                </div>
                <div class="form-group">
            التخزين
                    <input asp-for="Storageu" class="form-control" />
                    <span asp-validation-for="Storageu" class="text-danger"></span>
                </div>
                <div class="form-group">
               الكاميرا
                    <input asp-for="Camerau" class="form-control" />
                    <span asp-validation-for="Camerau" class="text-danger"></span>
                </div>
                <div class="form-group">
                  الصورة
                    <input type="file" name="File" asp-for="File" class="form-control" />
                    <span asp-validation-for="File" class="text-danger"></span>
                </div>
                <div class="form-group">
              اللون
                    <input asp-for="Color" class="form-control" />
                    <span asp-validation-for="Color" class="text-danger"></span>
                </div>
                <div class="form-group">
               الشاشه
                    <input asp-for="Display" class="form-control" />
                    <span asp-validation-for="Display" class="text-danger"></span>
                </div>
                <div class="form-group">
                 البطارية
                    <input asp-for="Battary" class="form-control" />
                    <span asp-validation-for="Battary" class="text-danger"></span>
                </div>
                <div class="form-group">
                تفاصيل اخرى
                    <input asp-for="AddDetails" class="form-control" />
                    <span asp-validation-for="AddDetails" class="text-danger"></span>
                </div>
                <div class="form-group">
                 السعر
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="حفظ" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a style="color:blueviolet" asp-action="Index">عودة</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</div>

FixFactorSystem/Views/UsedPhoneDetails/Index.cshtml
@model IEnumerable<FixFactorSystem.Models.UsedPhoneDetails>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h1 style="font-family: “Droid Arabic Kufi”, serif; text-align: center; margin-left: 100px; margin-top: 20px; font-weight: bold">مواصفات الهاتف</h1>

    <form class="c"   style="margin-left: 590px;"asp-controller="UsedPhoneDetails" asp-action="Create">

        <input type="submit" value="اضافة" class="btn btn-primary" />
    </form>


    <table class="table table-hover table table-striped table-dark" table-active" style="direction:rtl; margin:5px;">
        <thead class="thead-dark"  style="text-align:center; font-family: “Droid Arabic Kufi”, serif;">
            <tr>
                <th>
             النوع
                </th>
                <th>
           الرام
                </th>
                <th>
          التخزين
                </th>
                <th>
               الكاميرا
                </th>
                <th>
                 الصورة
                </th>
                <th>
                اللون
                </th>
                <th>
                 الشاشة
                </th>
                <th>
              البطارية
                </th>
                <th>
           مواصفات اخرى
                </th>
                <th>
                  السعر
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.MobNameu)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ramu)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Storageu)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Camerau)
                    </td>
                    <td>
                        <img src="~/Mobimg/@item.Imgu" style="width:80px; height:80px" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Color)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Display)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Battary) مللي أمبير
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AddDetails)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price) جنيه
                    </td>
                    <td>
                        <a style="color:darkorchid" asp-action="Edit" asp-route-id="@item.Idu">Edit</a> |
                        <a style="color:darkorchid" asp-action="Details" asp-route-id="@item.Idu">Details</a> |
                        <a style="color:darkorchid" asp-action="Delete" asp-route-id="@item.Idu">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>