FixFactorSystem/Models/NewPhoneDetails.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FixFactorSystem.Models
{
    public partial class NewPhoneDetails
    {
        public int Id { get; set; }
        public string MobName { get; set; }
        public string Ram { get; set; }
        public string Storage { get; set; }
        public string Camera { get; set; }
        public string Image { get; set; }
        public string Color { get; set; }
        public string Display { get; set; }
        public string Battary { get; set; }
        public string AddDetails { get; set; }
        public int? Price { get; set; }
        [NotMapped]
        public IFormFile File { get; set; }
    }
}

FixFactorSystem/Controllers/NewPhoneDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FixFactorSystem.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace FixFactorSystem.Controllers
{
    public class NewPhoneDetailsController : Controller
    {
        private readonly PhoneShopContext _context;
        private readonly IWebHostEnvironment hosting;
        public NewPhoneDetailsController(PhoneShopContext context, IWebHostEnvironment hosting)
        {
            _context = context;
            this.hosting = hosting;
        }

        // GET: NewPhoneDetails
        public async Task<IActionResult> Index()
        {
            return View(await _context.NewPhoneDetails.ToListAsync());
        }

        // GET: NewPhoneDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newPhoneDetails = await _context.NewPhoneDetails
                .FirstOrDefaultAsync(m => m.Id == id);
            if (newPhoneDetails == null)
            {
                return NotFound();
            }

            return View(newPhoneDetails);
        }

        // GET: NewPhoneDetails/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: NewPhoneDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MobName,Ram,Storage,Camera,Image,Color,Display,Battary,AddDetails,Price,File")] NewPhoneDetails newPhoneDetails)
        {
            if (ModelState.IsValid)
            {

                if (newPhoneDetails.File != null)
                {


                    String rotpath = hosting.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(newPhoneDetails.File.FileName);
                    string extention = Path.GetExtension(newPhoneDetails.File.FileName);
                    newPhoneDetails.Image = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extention;
                    string path = Path.Combine(rotpath + "/Mobimg", fileName);

                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await newPhoneDetails.File.CopyToAsync(fileStream);

                    }

                   
                    _context.Add(newPhoneDetails);
                    await _context.SaveChangesAsync();
                   // NewPhone newPhone = TempData["mydata"] as NewPhone;
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(newPhoneDetails);
        }

        // GET: NewPhoneDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newPhoneDetails = await _context.NewPhoneDetails.FindAsync(id);
            if (newPhoneDetails == null)
            {
                return NotFound();
            }
            return View(newPhoneDetails);
        }

        // POST: NewPhoneDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MobName,Ram,Storage,Camera,File,Color,Display,Battary,AddDetails,Price")] NewPhoneDetails newPhoneDetails)
        {
            if (id != newPhoneDetails.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (newPhoneDetails.File != null)
                    {


                        String rotpath = hosting.WebRootPath;
                        string fileName = Path.GetFileNameWithoutExtension(newPhoneDetails.File.FileName);
                        string extention = Path.GetExtension(newPhoneDetails.File.FileName);
                        newPhoneDetails.Image = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extention;
                        string path = Path.Combine(rotpath + "/Mobimg", fileName);

                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            await newPhoneDetails.File.CopyToAsync(fileStream);

                        }
                        _context.Update(newPhoneDetails);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewPhoneDetailsExists(newPhoneDetails.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(newPhoneDetails);
        }

        // GET: NewPhoneDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newPhoneDetails = await _context.NewPhoneDetails
                .FirstOrDefaultAsync(m => m.Id == id);
            if (newPhoneDetails == null)
            {
                return NotFound();
            }

            return View(newPhoneDetails);
        }

        // POST: NewPhoneDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var newPhoneDetails = await _context.NewPhoneDetails.FindAsync(id);
            _context.NewPhoneDetails.Remove(newPhoneDetails);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NewPhoneDetailsExists(int id)
        {
            return _context.NewPhoneDetails.Any(e => e.Id == id);
        }
    }
}

FixFactorSystem/Views/NewPhoneDetails/Create.cshtml
@model FixFactorSystem.Models.NewPhoneDetails

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
   

    <h2 style="color:blueviolet; margin:20px;font-weight:bold">اضافة هاتف جديد</h2>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                النوع
                    <input asp-for="MobName" class="form-control" />
                    <span asp-validation-for="MobName" class="text-danger"></span>
                </div>
                <div class="form-group">
                الرام
                    <input asp-for="Ram" class="form-control" />
                    <span asp-validation-for="Ram" class="text-danger"></span>
                </div>
                <div class="form-group">
                   التخزين
                    <input asp-for="Storage" class="form-control" />
                    <span asp-validation-for="Storage" class="text-danger"></span>
                </div>
                <div class="form-group">
                الكاميرا
                    <input asp-for="Camera" class="form-control" />
                    <span asp-validation-for="Camera" class="text-danger"></span>
                </div>
                <div class="form-group">
                  صورة
                    <input type="file" name="File" asp-for="File" class="form-control" />
                    <span asp-validation-for="File" class="text-danger"></span>
                </div>
                <div class="form-group">
               اللون
                    <input asp-for="Color" class="form-control" />
                    <span asp-validation-for="Color" class="text-danger"></span>
                </div>
                <div class="form-group">
           الشاشة
                    <input asp-for="Display" class="form-control" />
                    <span asp-validation-for="Display" class="text-danger"></span>
                </div>
                <div class="form-group">
                  البطاريه
                    <input asp-for="Battary" class="form-control" />
                    <span asp-validation-for="Battary" class="text-danger"></span>
                </div>
                <div class="form-group">
                 تفاصيل اخرى
                    <input asp-for="AddDetails" class="form-control" />
                    <span asp-validation-for="AddDetails" class="text-danger"></span>
                </div>
                <div class="form-group">
              السعر
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="اضافه" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a style="color:blueviolet" asp-action="Index">عوده</a>
    </div>
</div>
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

FixFactorSystem/Views/NewPhoneDetails/Delete.cshtml
@model FixFactorSystem.Models.NewPhoneDetails

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
  
    <h2 style="color:blueviolet; margin:20px;font-weight:bold">مسح الهاتف</h2>
    <h3>هل تريد مسح الهاتف</h3>
    <div>
      
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                النوع
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.MobName)
            </dd>
            <dt class="col-sm-2">
                الرام
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Ram)
            </dd>
            <dt class="col-sm-2">
                التخزين
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Storage)
            </dd>
            <dt class="col-sm-2">
                الكاميرا
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Camera)
            </dd>


            <dt class="col-sm-2">
                اللون
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Color)
            </dd>
            <dt class="col-sm-2">
                الشاشة
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Display)
            </dd>
            <dt class="col-sm-2">
                البطارية
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Battary)
            </dd>
            <dt class="col-sm-2">
                اخرى
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.AddDetails)
            </dd>
            <dt class="col-sm-2">
                السعر
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Price)
            </dd>
            <dt class="col-sm-2">

            </dt>
            <dd class="col-sm-10">
                @if (Model.Image != null)
                {


                    <img src="~/Mobimg/@Model.Image" style="width:300px; height:450px" />
                }

            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="مسح" class="btn btn-danger" /> |
            <a asp-action="Index">عودة</a>
        </form>
    </div>
</div>

FixFactorSystem/Views/NewPhoneDetails/Details.cshtml
@model FixFactorSystem.Models.NewPhoneDetails

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="features" style="        font-family: “Droid Arabic Kufi”, serif;
        color: #7c795d;
        margin: 5px;
        direction: rtl;
        text-align: right;
">
    <div class="container">
        <div class="feat" style=" float: right; width:50%">

            <h1 style="        color: darkmagenta ;
        text-align: right; direction: rtl;
        margin: 10px;
        font-weight: bold">
                تفاصيل
            </h1>

            <dl class="row" style=" direction:rtl; ">
                <dt class="col-lg-2">
                    النوع
                </dt>
                <dd class="col-sm-10" style=" ">
                    @Html.DisplayFor(model => model.MobName)
                </dd>
                <dt class="col-sm-2">
                    الرام
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Ram)
                </dd>
                <dt class="col-sm-2">
                    التخزين
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Storage)
                </dd>
                <dt class="col-sm-2">
                    الكاميرا
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Camera)
                </dd>

                <dt class="col-sm-2">
                    اللون
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Color)
                </dd>
                <dt class="col-sm-2">
                    الشاشه
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Display)
                </dd>
                <dt class="col-sm-2">
                    البطاريه
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Battary) مللي أمبير
                </dd>
                <dt class="col-sm-2">
                    تفاصيل
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.AddDetails)
                </dd>
                <dt class="col-sm-2">
                    السعر
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Price) جنيه
                </dd>
            </dl>
        </div>
        <div class="feat" style=" float: right; width:50%">
            <dl>
                <dt class="col-sm-2">

                </dt>
                <dd class="col-sm-10">
                    @if (Model.Image != null)
                    {


                        <img src="~/Mobimg/@Model.Image" style="width:300px; height:450px" />
                    }
                </dd>
            </dl>
        </div>
        <div class="ff" style=" margin-right:250px; margin-bottom:700px;">
            <div>
                <a style="color:blueviolet" asp-action="Edit" asp-route-id="@Model.Id">تعديل</a> |
                <a style="color:blueviolet" asp-action="Index">رجوع</a>
            </div>

        </div>

    </div>
</div>
    

FixFactorSystem/Views/NewPhoneDetails/Edit.cshtml
@model FixFactorSystem.Models.NewPhoneDetails

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
   
    <h2 style="color:blueviolet; margin:20px;font-weight:bold">تعديل مواصفات الهاتف</h2>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
               النوع
                    <input asp-for="MobName" class="form-control" />
                    <span asp-validation-for="MobName" class="text-danger"></span>
                </div>
                <div class="form-group">
               الرام
                    <input asp-for="Ram" class="form-control" />
                    <span asp-validation-for="Ram" class="text-danger"></span>
                </div>
                <div class="form-group">
              التخزين
                    <input asp-for="Storage" class="form-control" />
                    <span asp-validation-for="Storage" class="text-danger"></span>
                </div>
                <div class="form-group">
                الكاميرا
                    <input asp-for="Camera" class="form-control" />
                    <span asp-validation-for="Camera" class="text-danger"></span>
                </div>
                <div class="form-group">
                 صورة
                    <input type="file" name="File" asp-for="File" class="form-control" />
                    <span asp-validation-for="File" class="text-danger"></span>
                </div>
                <div class="form-group">
                   اللون
                    <input asp-for="Color" class="form-control" />
                    <span asp-validation-for="Color" class="text-danger"></span>
                </div>
                <div class="form-group">
                  الشاشه
                    <input asp-for="Display" class="form-control" />
                    <span asp-validation-for="Display" class="text-danger"></span>
                </div>
                <div class="form-group">
                البطاريه
                    <input asp-for="Battary" class="form-control" />
                    <span asp-validation-for="Battary" class="text-danger"></span>
                </div>
                <div class="form-group">
              مواصفات اخرى
                    <input asp-for="AddDetails" class="form-control" />
                    <span asp-validation-for="AddDetails" class="text-danger"></span>
                </div>
                <div class="form-group">
                السعر
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="حفظ" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a style="color:blueviolet" asp-action="Index">عوده</a>
    </div>
</div>
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

FixFactorSystem/Views/NewPhoneDetails/Index.cshtml
@model IEnumerable<FixFactorSystem.Models.NewPhoneDetails>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h1 style="font-family: “Droid Arabic Kufi”, serif; text-align: center; margin-left: 100px; margin-top: 20px; font-weight: bold">مواصفات الهاتف</h1>

    <form class="c" style="margin-left: 590px;" asp-controller="NewPhoneDetails" asp-action="Create">

        <input type="submit" value="اضافه" class="btn btn-primary" />
    </form>

    


    <table class="table table-hover table table-striped table-dark" table-active" style="direction:rtl; margin:5px;">
        <thead class="thead-dark" style="text-align:center; font-family: “Droid Arabic Kufi”, serif;">
            <tr>
                <th>
                    النوع
                </th>
                <th>
                    الرام
                </th>
                <th>
                    التخزين
                </th>
                <th>
                    الكاميرا
                </th>

                <th>
                    اللون
                </th>
                <th>
                    الشاشه
                </th>
                <th>
                    البطاريه
                </th>
                <th>
                    تفاصيل اخرى
                </th>
                <th>
                    السعر
                </th>
                <th>
                    صورة الجهاز
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.MobName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ram)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Storage)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Camera)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Color)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Display)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Battary) مللي أمبير
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AddDetails)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price) جنيه
                    </td>
                    <td>
                        <img src="~/Mobimg/@item.Image" style="width:80px; height:80px" />
                    </td>
                    <td>
                        <a style="color:darkorchid" asp-action="Edit" asp-route-id="@item.Id">تعديل</a> |
                        <a style="color:darkorchid" asp-action="Details" asp-route-id="@item.Id">تفاصيل</a> |
                        <a style="color:darkorchid" asp-action="Delete" asp-route-id="@item.Id">مسح</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>